Server:
  port: 8103

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dogservice?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: bootadmin
    password: 1234
  thymeleaf:
    cache: false

  #JPA 관련 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
